controller_list:
  - name: fake_welding_controller
    joints:
      - joint_1
      - joint_2
      - joint_7
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - torch_tip
  - name: fake_scanner_controller
    joints:
      - joint_1
      - joint_2
      - joint_7
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - scanner_tip