welding:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_search_resolution: 0.010
  kinematics_solver_timeout: 0.010
  kinematics_solver_attempts: 20
scanner:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_search_resolution: 0.010
  kinematics_solver_timeout: 0.010
  kinematics_solver_attempts: 20